/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Init */
        post: operations["pair_init_auth_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pair Poll */
        get: operations["pair_poll_auth_pair__challenge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/{challenge_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Deny */
        post: operations["pair_deny_auth_pair__challenge_id__deny_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Me */
        get: operations["session_me_auth_sessions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description Surface in-progress pairings to authorized clients (the webapp
         *     'pending devices' panel). Bare list — pending and approved
         *     challenges only; terminal records GC themselves.
         */
        get: operations["list_pending_auth_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Public liveness probe — minimal, no host identity, no auth.
         *
         *     Two fields: ``status`` and ``version``. Hostname / username /
         *     uptime live behind ``/whoami`` because they identify *who*
         *     runs the daemon.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Authenticated daemon identity + uptime.
         *
         *     Distinct from ``/auth/sessions/me`` (caller session) — this
         *     endpoint describes the daemon process itself.
         */
        get: operations["whoami_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_workspaces__ws_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Workspace
         * @description Partial metadata update — title and/or description.
         *
         *     Wire semantics: ``null`` / omitted = "do not change". Empty
         *     string in ``description`` clears it; title cannot be cleared.
         *     Mapping wire → engine kwargs: an absent field translates to
         *     "kwarg not passed" so the manager's ``_UNSET`` sentinel works.
         */
        patch: operations["update_workspace_workspaces__ws_id__patch"];
        trace?: never;
    };
    "/workspaces/{ws_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Workspace */
        post: operations["pause_workspace_workspaces__ws_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Workspace */
        post: operations["resume_workspace_workspaces__ws_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/respawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respawn Workspace */
        post: operations["respawn_workspace_workspaces__ws_id__respawn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Workspace */
        post: operations["kill_workspace_workspaces__ws_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attach Workspace */
        get: operations["attach_workspace_workspaces__ws_id__attach_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Peek Workspace */
        get: operations["peek_workspace_workspaces__ws_id__peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Commits
         * @description Comprehensive branch history (``git log base..branch``).
         *
         *     Distinct from ``peek.recent_commits`` which is a tight 3-row
         *     rail summary walking all of branch history. This route returns
         *     every commit done in the workspace since fork from base, newest
         *     first, uncapped — the detail-page consumer wants the full log.
         *     Best-effort like peek; never raises, returns ``[]`` on failure.
         */
        get: operations["workspace_commits_workspaces__ws_id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Branches */
        get: operations["list_branches_branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachInstructionView
         * @description Wire mirror of ``grove.core.tmux.AttachInstruction``.
         */
        AttachInstructionView: {
            /** Tmux Session */
            tmux_session: string;
            /** Inside Outer Tmux */
            inside_outer_tmux: boolean;
        };
        /**
         * AutoBranch
         * @description Grove generates ``{branch_prefix}{slug(title)}-{ts}`` off ``base_ref``.
         *
         *     The default create behavior — the same shape Grove ships today, now
         *     explicit. ``base_ref`` accepts any git revision (branch, tag, sha,
         *     ``HEAD``, ``origin/main``); validation that it actually exists happens
         *     in the engine when ``create()`` runs, so this Pydantic shape stays
         *     repo-agnostic and serializable.
         */
        AutoBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "auto";
            /**
             * Base Ref
             * @default HEAD
             */
            base_ref: string;
        };
        /**
         * BranchInfo
         * @description One branch entry as seen by the engine.
         *
         *     A ``BranchInfo`` is a snapshot — it is correct only for the moment it
         *     was read. Callers that show it in a UI should re-read after every
         *     workspace lifecycle event so stale entries (a branch checked out
         *     elsewhere a moment ago, now free) don't mislead the user.
         */
        BranchInfo: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "remote";
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Upstream */
            upstream?: string | null;
            /** Checked Out In */
            checked_out_in?: string | null;
        };
        BranchPlan: components["schemas"]["AutoBranch"] | components["schemas"]["NewNamedBranch"] | components["schemas"]["ExistingLocalBranch"] | components["schemas"]["TrackRemoteBranch"];
        /**
         * BranchProvenance
         * @description Whether Grove created this workspace's branch or the user attached one.
         *
         *     Drives the kill-confirm default and the rollback-on-create-failure
         *     policy. Persisted on every `WorkspaceState`. The principle is that
         *     Grove manages the worktree always; the branch is the user's domain
         *     when they attached it, and Grove's only when Grove created it. The
         *     remote is never touched in either case — that is `git push --delete`
         *     territory and stays in the user's shell.
         * @enum {string}
         */
        BranchProvenance: "grove" | "attached";
        /**
         * ChallengeState
         * @description Lifecycle states for a `PairingChallenge`.
         *
         *     Persisted to JSON. ``StrEnum`` keeps the on-disk value plain.
         * @enum {string}
         */
        ChallengeState: "pending" | "approved" | "denied" | "consumed" | "expired";
        /**
         * CommitSummaryView
         * @description Wire mirror of ``grove.core.workspace.CommitSummary``.
         */
        CommitSummaryView: {
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
        };
        /**
         * CreateWorkspaceRequest
         * @description Payload for ``WorkspaceManager.create()``.
         *
         *     ``branch_plan`` defaults to ``AutoBranch()`` so callers that don't
         *     care about branch semantics get the historical Grove behavior for
         *     free — Grove generates ``{prefix}{slug(title)}-{ts}`` off ``HEAD``.
         */
        CreateWorkspaceRequest: {
            /** Agent Name */
            agent_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            branch_plan?: components["schemas"]["BranchPlan"];
            /** Repo Root */
            repo_root?: string | null;
        };
        /**
         * ExistingLocalBranch
         * @description Check out an existing local branch into a new worktree.
         *
         *     No new branch is created. Provenance is ``USER_ATTACHED`` so kill
         *     defaults to keeping the branch — this is the user's pre-existing
         *     feature branch and a workspace tear-down must not lose it.
         */
        ExistingLocalBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "existing_local";
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthView
         * @description Public liveness probe — unauthenticated, no host identity.
         *
         *     Returned by ``GET /healthz``. Two fields only:
         *
         *     - ``status``: literal ``"ok"`` while the process answers requests.
         *       Reserved as a literal so future degraded states (e.g. ``"draining"``)
         *       can be added without breaking the discriminator on clients.
         *     - ``version``: ``grove.__version__``. Public-safe — already advertised
         *       in ``/openapi.json``'s ``info.version``.
         *
         *     Deliberately omits hostname, username, started_at, uptime — those
         *     identify *who* runs the daemon and live behind auth in
         *     :class:`WhoamiView`.
         */
        HealthView: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * InitStatus
         * @description Outcome of the init script for one workspace, persisted on `WorkspaceState`.
         * @enum {string}
         */
        InitStatus: "ok" | "failed" | "skipped";
        /**
         * NewNamedBranch
         * @description User-supplied branch name, off ``base_ref``.
         *
         *     Grove still owns the worktree path and tmux session names (they follow
         *     ``slug(title)``); only the branch is the user's namespace. The pattern
         *     accepts alphanumerics, dot, dash, underscore, slash; rejects a leading
         *     dash so the value can never be parsed as a CLI flag downstream.
         */
        NewNamedBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "new_named";
            /** Name */
            name: string;
            /**
             * Base Ref
             * @default HEAD
             */
            base_ref: string;
        };
        /**
         * PairRequest
         * @description ``POST /auth/pair`` body.
         */
        PairRequest: {
            /** Label */
            label: string;
        };
        /**
         * PairResultView
         * @description Polling response — carries the bearer token only on the consume step.
         */
        PairResultView: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            state: components["schemas"]["ChallengeState"];
            /** Token */
            token?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * PairingChallengeView
         * @description Read-only view of a `PairingChallenge` for HTTP responses + the TUI.
         */
        PairingChallengeView: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Label */
            label: string;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            state: components["schemas"]["ChallengeState"];
        };
        /**
         * SessionView
         * @description Read-only summary of a session — never exposes ``token_hash``.
         */
        SessionView: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Revoked
             * @default false
             */
            revoked: boolean;
        };
        /**
         * TrackRemoteBranch
         * @description Track a remote branch by creating a fresh local tracking branch.
         *
         *     ``remote_ref`` is the full remote-qualified ref (e.g. ``origin/feature/x``).
         *     ``local_name`` defaults to the part after the first ``/`` — strip the
         *     remote name and use whatever's left. Provenance is ``GROVE_CREATED``
         *     because the local branch is fresh: if the user later kills the
         *     workspace and the local branch goes with it, the remote ref still
         *     has every commit (and they can re-track at any time).
         */
        TrackRemoteBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "track_remote";
            /** Remote Ref */
            remote_ref: string;
            /** Local Name */
            local_name?: string | null;
        };
        /**
         * UpdateWorkspaceRequest
         * @description Payload for ``WorkspaceManager.update()`` — partial metadata edit.
         *
         *     Wire semantics: ``null`` (or field omitted) means "do not change".
         *     To clear an existing description, send ``""``. Title cannot be
         *     cleared — workspaces are required to have a non-empty title at all
         *     times.
         *
         *     The model validator refuses an entirely-empty body so callers can't
         *     issue a no-op PATCH that bumps ``updated_at`` for free; the engine
         *     has its own no-op short-circuit for "values match current", but this
         *     catches the obvious "forgot to set anything" client bug at the
         *     request boundary.
         */
        UpdateWorkspaceRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhoamiView
         * @description Authenticated daemon identity + uptime.
         *
         *     Returned by ``GET /whoami``. Distinct from
         *     ``GET /auth/sessions/me`` (which describes the *calling session*) —
         *     this one answers "who is the daemon, on what host, since when."
         *
         *     All fields are populated server-side from stdlib (``socket``,
         *     ``getpass``, ``platform``) and the lifespan-captured ``started_at``;
         *     the view itself is pure data with no engine coupling.
         */
        WhoamiView: {
            /** Version */
            version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Host */
            host: string;
            /** User */
            user: string;
            /** Platform */
            platform: string;
            /** Python Version */
            python_version: string;
        };
        /**
         * WorkspacePeekView
         * @description Wire mirror of ``grove.core.workspace.WorkspacePeek``.
         */
        WorkspacePeekView: {
            state: components["schemas"]["WorkspaceStateView"];
            /** Base Ahead */
            base_ahead: number;
            /** Base Behind */
            base_behind: number;
            /** Diff Added */
            diff_added: number;
            /** Diff Removed */
            diff_removed: number;
            /** Dirty Files */
            dirty_files: number;
            /** Recent Commits */
            recent_commits: components["schemas"]["CommitSummaryView"][];
            /** Agent Snapshot */
            agent_snapshot: string | null;
            /** Snapshot Taken At */
            snapshot_taken_at: string | null;
        };
        /**
         * WorkspaceStateView
         * @description Wire mirror of ``grove.core.workspace.WorkspaceState``.
         */
        WorkspaceStateView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Repo Root */
            repo_root: string;
            /** Branch */
            branch: string;
            /** Base Branch */
            base_branch: string;
            /** Worktree Path */
            worktree_path: string;
            /** Tmux Session */
            tmux_session: string;
            /** Agent Name */
            agent_name: string;
            status: components["schemas"]["WorkspaceStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Paused At */
            paused_at?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Description */
            description?: string | null;
            init_status?: components["schemas"]["InitStatus"] | null;
            /** Init Duration Ms */
            init_duration_ms?: number | null;
            /** @default grove */
            branch_provenance: components["schemas"]["BranchProvenance"];
        };
        /**
         * WorkspaceStatus
         * @description Workspace status — split into persistent intents and computed views.
         *
         *     Three values are persistent intents: lifecycle methods write them to JSON
         *     and `JsonWorkspaceStore` rejects writes of any other value (defense in
         *     depth). The remaining four are derived at read time by
         *     `WorkspaceManager._reconcile_status` from the persistent intent + tmux
         *     session presence + worktree presence + tmux pane activity. `list()` and
         *     `peek()` always promote intents to displayed values, so callers reading
         *     through the manager see ACTIVE/IDLE/OFFLINE/PAUSED/ORPHANED/ERROR — never
         *     the raw RUNNING intent.
         * @enum {string}
         */
        WorkspaceStatus: "running" | "paused" | "error" | "active" | "idle" | "offline" | "orphaned";
        /**
         * _KillBody
         * @description Kill request body — ``delete_branch=None`` defers to the workspace's branch_provenance.
         *
         *     Module-scope for the same reason as ``_PauseBody`` above.
         */
        _KillBody: {
            /** Delete Branch */
            delete_branch?: boolean | null;
        };
        /**
         * _PauseBody
         * @description Pause request body — ``force`` skips the dirty-worktree check.
         *
         *     Module-scope (not a ``build_app`` closure): under ``from __future__ import
         *     annotations`` FastAPI / Pydantic can't resolve a closure-defined model
         *     referenced by string forward-ref in a route handler signature, which
         *     surfaces as a ``PydanticUserError`` on the first request. Module-top
         *     keeps the introspection deterministic; the underscore prefix marks the
         *     class as daemon-internal so it doesn't leak into the public surface.
         */
        _PauseBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pair_init_auth_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingChallengeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_poll_auth_pair__challenge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResultView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_deny_auth_pair__challenge_id__deny_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
        };
    };
    session_me_auth_sessions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    revoke_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_auth_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingChallengeView"][];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    whoami_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiView"];
                };
            };
        };
    };
    list_workspaces_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"][];
                };
            };
        };
    };
    create_workspace_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_workspaces__ws_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_workspaces__ws_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_workspace_workspaces__ws_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_PauseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_workspace_workspaces__ws_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respawn_workspace_workspaces__ws_id__respawn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_workspace_workspaces__ws_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_KillBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_workspace_workspaces__ws_id__attach_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachInstructionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peek_workspace_workspaces__ws_id__peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePeekView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_commits_workspaces__ws_id__commits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitSummaryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_branches_branches_get: {
        parameters: {
            query: {
                repo: string;
                scope: "local" | "remote";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
