/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Init */
        post: operations["pair_init_auth_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pair Poll */
        get: operations["pair_poll_auth_pair__challenge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/{challenge_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Deny */
        post: operations["pair_deny_auth_pair__challenge_id__deny_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Me */
        get: operations["session_me_auth_sessions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description Surface in-progress pairings to authorized clients (the webapp
         *     'pending devices' panel). Bare list — pending and approved
         *     challenges only; terminal records GC themselves.
         */
        get: operations["list_pending_auth_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Public liveness probe — minimal, no host identity, no auth.
         *
         *     Two fields: ``status`` and ``version``. Hostname / username /
         *     uptime live behind ``/whoami`` because they identify *who*
         *     runs the daemon.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Authenticated daemon identity + uptime.
         *
         *     Distinct from ``/auth/sessions/me`` (caller session) — this
         *     endpoint describes the daemon process itself.
         */
        get: operations["whoami_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description One-shot cross-project dashboard snapshot.
         *
         *     ``snapshot()`` does blocking git/tmux I/O, so it runs in the executor to
         *     keep the loop responsive under concurrent requests.
         */
        get: operations["activity_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE activity stream: a snapshot on connect, then live deltas.
         *
         *     Bridges the per-connection bounded queue (via ``_SseHub``) to the wire.
         *     Reconnects carrying ``Last-Event-ID`` replay missed deltas from the ring
         *     buffer when the gap is small enough; otherwise they get a fresh snapshot.
         *     A wedged client only ever loses its own buffered events (drop-oldest),
         *     never back-pressures the engine.
         *
         *     Auth is the normal bearer dependency: a browser ``EventSource`` can't set
         *     headers, so the webapp's BFF calls this server-side with the token and the
         *     browser authenticates to the BFF by cookie — the token never reaches the
         *     browser.
         */
        get: operations["events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_workspaces__ws_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Workspace
         * @description Partial metadata update — title and/or description.
         *
         *     Wire semantics: ``null`` / omitted = "do not change". Empty
         *     string in ``description`` clears it; title cannot be cleared.
         *     Mapping wire → engine kwargs: an absent field translates to
         *     "kwarg not passed" so the manager's ``_UNSET`` sentinel works.
         */
        patch: operations["update_workspace_workspaces__ws_id__patch"];
        trace?: never;
    };
    "/workspaces/{ws_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Workspace */
        post: operations["pause_workspace_workspaces__ws_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Workspace */
        post: operations["resume_workspace_workspaces__ws_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/respawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respawn Workspace */
        post: operations["respawn_workspace_workspaces__ws_id__respawn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Workspace */
        post: operations["kill_workspace_workspaces__ws_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attach Workspace */
        get: operations["attach_workspace_workspaces__ws_id__attach_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Peek Workspace */
        get: operations["peek_workspace_workspaces__ws_id__peek_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/pane": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Pane
         * @description One-shot agent-pane ANSI snapshot for the dashboard's focused live pane (#19).
         *
         *     The web dashboard polls this for the single expanded card (status-gated to
         *     WORKING) instead of mounting N live terminals — the peer-validated "summary
         *     wall + one live focus" shape. Best-effort like peek; never raises (returns
         *     ``ansi: null`` when the session isn't live).
         */
        get: operations["workspace_pane_workspaces__ws_id__pane_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Commits
         * @description Comprehensive branch history (``git log base..branch``).
         *
         *     Distinct from ``peek.recent_commits`` which is a tight 3-row
         *     rail summary walking all of branch history. This route returns
         *     every commit done in the workspace since fork from base, newest
         *     first, uncapped — the detail-page consumer wants the full log.
         *     Best-effort like peek; never raises, returns ``[]`` on failure.
         */
        get: operations["workspace_commits_workspaces__ws_id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Sessions
         * @description Every agent session recorded for the workspace's directory, newest-first.
         *
         *     Fetch-on-demand by design — session history never rides the SSE stream.
         *     The scan full-parses each transcript in one cwd (the documented
         *     ``list_sessions`` cost model), so it runs in the executor like
         *     ``/activity``.
         */
        get: operations["workspace_sessions_workspaces__ws_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{ws_id}/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Session Turns
         * @description The session's conversation, oldest-first; ``last`` keeps only the tail.
         *
         *     ``session_id`` must be the full id (clients hold it from the sessions
         *     listing) — prefix resolution stays a CLI affordance. 404
         *     ``agent_session_not_found`` when the id isn't recorded for this
         *     workspace.
         */
        get: operations["workspace_session_turns_workspaces__ws_id__sessions__session_id__turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Branches */
        get: operations["list_branches_branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentActivityState
         * @description What one agent session is doing right now (epic #11 §6).
         *
         *     Computed live from the transcript blended with tmux activity; never
         *     persisted. The transcript-only adapter emits a subset (WORKING / WAITING /
         *     ERROR / UNKNOWN); the ``ActivityService`` is the single policy site that
         *     layers in STARTING (session id known, no file yet), IDLE (alive but tmux
         *     quiet), and — once #18 lands — BLOCKED (permission prompt from a hook).
         * @enum {string}
         */
        AgentActivityState: "starting" | "working" | "waiting" | "blocked" | "idle" | "error" | "unknown";
        /**
         * AgentActivityView
         * @description Wire mirror of ``grove.core.agents.AgentActivity`` (``needs_attention`` materialized).
         */
        AgentActivityView: {
            state: components["schemas"]["AgentActivityState"];
            /** Title */
            title: string | null;
            /** Current Task */
            current_task: string | null;
            /** Human Turns */
            human_turns: number;
            /** Assistant Replies */
            assistant_replies: number;
            /** Replies Per Turn */
            replies_per_turn: number[];
            /** Tool Calls */
            tool_calls: number;
            /** Model */
            model: string | null;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Last Event At */
            last_event_at: string | null;
            /** Needs Attention */
            needs_attention: boolean;
            /** Error Detail */
            error_detail: string | null;
            /** Interpreted Status */
            interpreted_status?: string | null;
        };
        /**
         * AgentSessionView
         * @description Wire mirror of ``grove.core.agents.AgentSession``.
         *
         *     ``transcript_path`` is deliberately absent: it is a host-private path
         *     (views never expose those), and no client ever consumed it — sessions are
         *     identified by id on the wire.
         */
        AgentSessionView: {
            /** Session Id */
            session_id: string;
            /** Adapter Kind */
            adapter_kind: string;
            /** Provenance */
            provenance: string;
            /** Tmux Window */
            tmux_window: string | null;
        };
        /**
         * AttachInstructionView
         * @description Wire mirror of ``grove.core.tmux.AttachInstruction``.
         */
        AttachInstructionView: {
            /** Tmux Session */
            tmux_session: string;
            /** Inside Outer Tmux */
            inside_outer_tmux: boolean;
        };
        /**
         * AutoBranch
         * @description Grove generates ``{branch_prefix}{slug(title)}-{ts}`` off ``base_ref``.
         *
         *     The default create behavior — the same shape Grove ships today, now
         *     explicit. ``base_ref`` accepts any git revision (branch, tag, sha,
         *     ``HEAD``, ``origin/main``); validation that it actually exists happens
         *     in the engine when ``create()`` runs, so this Pydantic shape stays
         *     repo-agnostic and serializable.
         */
        AutoBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "auto";
            /**
             * Base Ref
             * @default HEAD
             */
            base_ref: string;
        };
        /**
         * BranchInfo
         * @description One branch entry as seen by the engine.
         *
         *     A ``BranchInfo`` is a snapshot — it is correct only for the moment it
         *     was read. Callers that show it in a UI should re-read after every
         *     workspace lifecycle event so stale entries (a branch checked out
         *     elsewhere a moment ago, now free) don't mislead the user.
         */
        BranchInfo: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "remote";
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Upstream */
            upstream?: string | null;
            /** Checked Out In */
            checked_out_in?: string | null;
        };
        BranchPlan: components["schemas"]["AutoBranch"] | components["schemas"]["NewNamedBranch"] | components["schemas"]["ExistingLocalBranch"] | components["schemas"]["TrackRemoteBranch"] | components["schemas"]["RootBranch"];
        /**
         * BranchProvenance
         * @description Whether Grove created this workspace's branch or the user attached one.
         *
         *     Drives the kill-confirm default and the rollback-on-create-failure
         *     policy. Persisted on every `WorkspaceState`. The principle is that
         *     Grove manages the worktree always; the branch is the user's domain
         *     when they attached it, and Grove's only when Grove created it. The
         *     remote is never touched in either case — that is `git push --delete`
         *     territory and stays in the user's shell.
         * @enum {string}
         */
        BranchProvenance: "grove" | "attached";
        /**
         * ChallengeState
         * @description Lifecycle states for a `PairingChallenge`.
         *
         *     Persisted to JSON. ``StrEnum`` keeps the on-disk value plain.
         * @enum {string}
         */
        ChallengeState: "pending" | "approved" | "denied" | "consumed" | "expired";
        /**
         * CommitSummaryView
         * @description Wire mirror of ``grove.core.workspace.CommitSummary``.
         */
        CommitSummaryView: {
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
        };
        /**
         * CreateWorkspaceRequest
         * @description Payload for ``WorkspaceManager.create()``.
         *
         *     ``branch_plan`` defaults to ``AutoBranch()`` so callers that don't
         *     care about branch semantics get the historical Grove behavior for
         *     free — Grove generates ``{prefix}{slug(title)}-{ts}`` off ``HEAD``.
         */
        CreateWorkspaceRequest: {
            /** Agent Name */
            agent_name: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            branch_plan?: components["schemas"]["BranchPlan"];
            /**
             * Skip Init
             * @default false
             */
            skip_init: boolean;
            /** Repo Root */
            repo_root?: string | null;
        };
        /**
         * DashboardEvent
         * @description The SSE streaming envelope (epic #11 §5).
         *
         *     One shape carries every server-sent kind. ``snapshot`` (sent on connect)
         *     embeds the full ``DashboardSnapshotView``; ``session_activity`` embeds the one
         *     changed ``WorkspaceActivityView`` so the client patches a single card;
         *     ``workspace_changed`` is a lifecycle wake-up (re-fetch); ``heartbeat`` keeps
         *     the connection warm; ``pane_snapshot`` is reserved for #19. ``seq`` is the
         *     monotonic SSE id used for ``Last-Event-ID`` replay.
         */
        DashboardEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "snapshot" | "workspace_changed" | "session_activity" | "pane_snapshot" | "heartbeat";
            /** Seq */
            seq: number;
            /** Workspace Id */
            workspace_id?: string | null;
            /** Repo Root */
            repo_root?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: string;
            };
            workspace?: components["schemas"]["WorkspaceActivityView"] | null;
            snapshot?: components["schemas"]["DashboardSnapshotView"] | null;
        };
        /**
         * DashboardSnapshotView
         * @description Wire mirror of ``grove.core.activity.DashboardSnapshot`` — one full render.
         */
        DashboardSnapshotView: {
            /** Projects */
            projects: components["schemas"]["ProjectGroupView"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total Workspaces */
            total_workspaces: number;
            /** Needs Attention */
            needs_attention: number;
        };
        /**
         * DigestEntryView
         * @description Wire mirror of ``grove.core.agents.DigestEntry`` (text capped).
         */
        DigestEntryView: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "tool" | "summary" | "status";
            /** Text */
            text: string;
        };
        /**
         * ExistingLocalBranch
         * @description Check out an existing local branch into a new worktree.
         *
         *     No new branch is created. Provenance is ``USER_ATTACHED`` so kill
         *     defaults to keeping the branch — this is the user's pre-existing
         *     feature branch and a workspace tear-down must not lose it.
         */
        ExistingLocalBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "existing_local";
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthView
         * @description Public liveness probe — unauthenticated, no host identity.
         *
         *     Returned by ``GET /healthz``. Two fields only:
         *
         *     - ``status``: literal ``"ok"`` while the process answers requests.
         *       Reserved as a literal so future degraded states (e.g. ``"draining"``)
         *       can be added without breaking the discriminator on clients.
         *     - ``version``: ``grove.__version__``. Public-safe — already advertised
         *       in ``/openapi.json``'s ``info.version``.
         *
         *     Deliberately omits hostname, username, started_at, uptime — those
         *     identify *who* runs the daemon and live behind auth in
         *     :class:`WhoamiView`.
         */
        HealthView: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * InitStatus
         * @description Outcome of the init script for one workspace, persisted on `WorkspaceState`.
         * @enum {string}
         */
        InitStatus: "ok" | "failed" | "skipped";
        /**
         * NewNamedBranch
         * @description User-supplied branch name, off ``base_ref``.
         *
         *     Grove still owns the worktree path and tmux session names (they follow
         *     ``slug(title)``); only the branch is the user's namespace. The pattern
         *     accepts alphanumerics, dot, dash, underscore, slash; rejects a leading
         *     dash so the value can never be parsed as a CLI flag downstream.
         */
        NewNamedBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "new_named";
            /** Name */
            name: string;
            /**
             * Base Ref
             * @default HEAD
             */
            base_ref: string;
        };
        /**
         * PairRequest
         * @description ``POST /auth/pair`` body.
         */
        PairRequest: {
            /** Label */
            label: string;
        };
        /**
         * PairResultView
         * @description Polling response — carries the bearer token only on the consume step.
         */
        PairResultView: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            state: components["schemas"]["ChallengeState"];
            /** Token */
            token?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * PairingChallengeView
         * @description Read-only view of a `PairingChallenge` for HTTP responses + the TUI.
         */
        PairingChallengeView: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Label */
            label: string;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            state: components["schemas"]["ChallengeState"];
        };
        /**
         * Placement
         * @description Where a workspace's tmux session is rooted, and what Grove manages for it.
         *
         *     The dimension orthogonal to status: it never changes after create() and
         *     decides which side effects each lifecycle method may fire. Lives here
         *     (not in `contracts/branch_plan.py`) because `branch_plan` imports *from*
         *     this module; the enum has to sit on the depended-upon side to avoid a
         *     cycle. `RootBranch.resolve()` is the only producer of `ROOT`.
         * @enum {string}
         */
        Placement: "worktree" | "root";
        /**
         * ProjectGroupView
         * @description Wire mirror of ``grove.core.activity.ProjectGroup``.
         */
        ProjectGroupView: {
            /** Repo Root */
            repo_root: string;
            /** Repo Name */
            repo_name: string;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceActivityView"][];
        };
        /**
         * RootBranch
         * @description Run the workspace in the repo root itself — no worktree, current branch.
         *
         *     The fifth variant is a placement choice, not a branch choice: it carries
         *     no user fields because there is nothing to source. The session is rooted at
         *     the repo, adopting whatever branch HEAD already points to; Grove creates no
         *     worktree and no branch, so kill never deletes anything and pause/resume are
         *     refused. This is "work in place on what I've already got out" — the escape
         *     hatch for users who don't want an isolated worktree per task.
         *
         *     `resolve()` returns a sentinel with an empty `name` (the manager fills it
         *     from live HEAD) and `provenance=USER_ATTACHED`, so even an explicit
         *     `delete_branch=True` on kill is overridden to False: the user's working
         *     branch is never Grove's to delete.
         */
        RootBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "root";
        };
        /**
         * SessionActivityView
         * @description Wire mirror of ``grove.core.activity.SessionActivity``.
         */
        SessionActivityView: {
            session: components["schemas"]["AgentSessionView"];
            activity: components["schemas"]["AgentActivityView"];
        };
        /**
         * SessionDetailView
         * @description One session with its conversation — the turns endpoint's response.
         */
        SessionDetailView: {
            session: components["schemas"]["SessionSummaryView"];
            /** Turns */
            turns: components["schemas"]["SessionTurnView"][];
        };
        /**
         * SessionSummaryView
         * @description Wire mirror of ``grove.core.sessions.SessionListing`` — one session row.
         *
         *     Flattens the listing's ``SessionSummary`` plus its project annotation.
         *     ``activity`` reuses the dashboard's ``AgentActivityView`` — the explorer's
         *     one parse per transcript yields both metadata and metrics, so the wire
         *     carries them together too.
         */
        SessionSummaryView: {
            /** Session Id */
            session_id: string;
            /** Adapter Kind */
            adapter_kind: string;
            /** Provenance */
            provenance: string;
            /** Workspace Id */
            workspace_id: string | null;
            /** Git Branch */
            git_branch: string | null;
            /** Created At */
            created_at: string | null;
            /** Modified At */
            modified_at: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Title */
            title: string | null;
            /** First Prompt */
            first_prompt: string | null;
            /** Last Prompt */
            last_prompt: string | null;
            activity: components["schemas"]["AgentActivityView"];
        };
        /**
         * SessionTurnView
         * @description Wire mirror of ``grove.core.agents.SessionTurn``.
         *
         *     ``user_text`` is empty for a leading continuation block (a resumed or
         *     compacted session's head) — same convention as the engine dataclass.
         */
        SessionTurnView: {
            /** User Text */
            user_text: string;
            /** Started At */
            started_at: string | null;
            /** Entries */
            entries: components["schemas"]["DigestEntryView"][];
        };
        /**
         * SessionView
         * @description Read-only summary of a session — never exposes ``token_hash``.
         */
        SessionView: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Revoked
             * @default false
             */
            revoked: boolean;
        };
        /**
         * TrackRemoteBranch
         * @description Track a remote branch by creating a fresh local tracking branch.
         *
         *     ``remote_ref`` is the full remote-qualified ref (e.g. ``origin/feature/x``).
         *     ``local_name`` defaults to the part after the first ``/`` — strip the
         *     remote name and use whatever's left. Provenance is ``GROVE_CREATED``
         *     because the local branch is fresh: if the user later kills the
         *     workspace and the local branch goes with it, the remote ref still
         *     has every commit (and they can re-track at any time).
         */
        TrackRemoteBranch: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "track_remote";
            /** Remote Ref */
            remote_ref: string;
            /** Local Name */
            local_name?: string | null;
        };
        /**
         * UpdateWorkspaceRequest
         * @description Payload for ``WorkspaceManager.update()`` — partial metadata edit.
         *
         *     Wire semantics: ``null`` (or field omitted) means "do not change".
         *     To clear an existing description, send ``""``. Title cannot be
         *     cleared — workspaces are required to have a non-empty title at all
         *     times.
         *
         *     The model validator refuses an entirely-empty body so callers can't
         *     issue a no-op PATCH that bumps ``updated_at`` for free; the engine
         *     has its own no-op short-circuit for "values match current", but this
         *     catches the obvious "forgot to set anything" client bug at the
         *     request boundary.
         */
        UpdateWorkspaceRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhoamiView
         * @description Authenticated daemon identity + uptime.
         *
         *     Returned by ``GET /whoami``. Distinct from
         *     ``GET /auth/sessions/me`` (which describes the *calling session*) —
         *     this one answers "who is the daemon, on what host, since when."
         *
         *     All fields are populated server-side from stdlib (``socket``,
         *     ``getpass``, ``platform``) and the lifespan-captured ``started_at``;
         *     the view itself is pure data with no engine coupling.
         */
        WhoamiView: {
            /** Version */
            version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Host */
            host: string;
            /** User */
            user: string;
            /** Platform */
            platform: string;
            /** Python Version */
            python_version: string;
        };
        /**
         * WorkspaceActivityView
         * @description Wire mirror of ``grove.core.activity.WorkspaceActivity`` — one dashboard card.
         *
         *     ``recent_commits`` is the durable latest-activity signal (newest first;
         *     ``recent_commits[0]`` is the card's "what was done, when committed" line).
         *     ``observed_at`` is the per-card "updated Xs ago"; the dashboard-wide refresh
         *     time stays on ``DashboardSnapshotView.generated_at``.
         */
        WorkspaceActivityView: {
            state: components["schemas"]["WorkspaceStateView"];
            /** Sessions */
            sessions: components["schemas"]["SessionActivityView"][];
            /** Base Ahead */
            base_ahead: number;
            /** Base Behind */
            base_behind: number;
            /** Diff Added */
            diff_added: number;
            /** Diff Removed */
            diff_removed: number;
            /** Dirty Files */
            dirty_files: number;
            /** Pane Target */
            pane_target: string | null;
            /** Needs Attention */
            needs_attention: boolean;
            /** Recent Commits */
            recent_commits: components["schemas"]["CommitSummaryView"][];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /**
         * WorkspacePaneView
         * @description One-shot ANSI snapshot of a workspace's agent tmux pane (#19).
         *
         *     The focused-pane source for the dashboard's "one live focus": a client polls
         *     this for the single expanded card (status-gated to WORKING) rather than
         *     mounting N live terminals. ``ansi`` is ``tmux capture-pane -e`` output (SGR
         *     only — safe to render as colored text or to strip); ``None`` when the session
         *     isn't live or has no pane. Best-effort like peek — the route never raises.
         */
        WorkspacePaneView: {
            /** Workspace Id */
            workspace_id: string;
            /** Ansi */
            ansi: string | null;
            /** Taken At */
            taken_at: string | null;
        };
        /**
         * WorkspacePeekView
         * @description Wire mirror of ``grove.core.workspace.WorkspacePeek``.
         */
        WorkspacePeekView: {
            state: components["schemas"]["WorkspaceStateView"];
            /** Base Ahead */
            base_ahead: number;
            /** Base Behind */
            base_behind: number;
            /** Diff Added */
            diff_added: number;
            /** Diff Removed */
            diff_removed: number;
            /** Dirty Files */
            dirty_files: number;
            /** Recent Commits */
            recent_commits: components["schemas"]["CommitSummaryView"][];
            /** Agent Snapshot */
            agent_snapshot: string | null;
            /** Snapshot Taken At */
            snapshot_taken_at: string | null;
        };
        /**
         * WorkspaceStateView
         * @description Wire mirror of ``grove.core.workspace.WorkspaceState``.
         */
        WorkspaceStateView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Repo Root */
            repo_root: string;
            /** Branch */
            branch: string;
            /** Base Branch */
            base_branch: string;
            /** Worktree Path */
            worktree_path: string;
            /** Tmux Session */
            tmux_session: string;
            /** Agent Name */
            agent_name: string;
            status: components["schemas"]["WorkspaceStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Paused At */
            paused_at?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Description */
            description?: string | null;
            init_status?: components["schemas"]["InitStatus"] | null;
            /** Init Duration Ms */
            init_duration_ms?: number | null;
            /** @default grove */
            branch_provenance: components["schemas"]["BranchProvenance"];
            /** @default worktree */
            placement: components["schemas"]["Placement"];
        };
        /**
         * WorkspaceStatus
         * @description Workspace status — split into persistent intents and computed views.
         *
         *     Three values are persistent intents: lifecycle methods write them to JSON
         *     and `JsonWorkspaceStore` rejects writes of any other value (defense in
         *     depth). The remaining four are derived at read time by
         *     `WorkspaceManager._reconcile_status` from the persistent intent + tmux
         *     session presence + worktree presence + tmux pane activity. `list()` and
         *     `peek()` always promote intents to displayed values, so callers reading
         *     through the manager see ACTIVE/IDLE/OFFLINE/PAUSED/ORPHANED/ERROR — never
         *     the raw RUNNING intent.
         * @enum {string}
         */
        WorkspaceStatus: "running" | "paused" | "error" | "active" | "idle" | "offline" | "orphaned";
        /**
         * _KillBody
         * @description Kill request body — ``delete_branch=None`` defers to the workspace's branch_provenance.
         *
         *     Module-scope for the same reason as ``_PauseBody`` above.
         */
        _KillBody: {
            /** Delete Branch */
            delete_branch?: boolean | null;
        };
        /**
         * _PauseBody
         * @description Pause request body — ``force`` skips the dirty-worktree check.
         *
         *     Module-scope (not a ``build_app`` closure): under ``from __future__ import
         *     annotations`` FastAPI / Pydantic can't resolve a closure-defined model
         *     referenced by string forward-ref in a route handler signature, which
         *     surfaces as a ``PydanticUserError`` on the first request. Module-top
         *     keeps the introspection deterministic; the underscore prefix marks the
         *     class as daemon-internal so it doesn't leak into the public surface.
         */
        _PauseBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pair_init_auth_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingChallengeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_poll_auth_pair__challenge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResultView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_deny_auth_pair__challenge_id__deny_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
        };
    };
    session_me_auth_sessions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    revoke_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_auth_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingChallengeView"][];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    whoami_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiView"];
                };
            };
        };
    };
    activity_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshotView"];
                };
            };
        };
    };
    events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of DashboardEvent JSON objects. The first frame is a `snapshot` (or a `Last-Event-ID` replay); subsequent frames are `session_activity` / `workspace_changed` deltas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEvent"];
                };
            };
        };
    };
    list_workspaces_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"][];
                };
            };
        };
    };
    create_workspace_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_workspaces__ws_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_workspaces__ws_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_workspace_workspaces__ws_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_PauseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_workspace_workspaces__ws_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respawn_workspace_workspaces__ws_id__respawn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_workspace_workspaces__ws_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_KillBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_workspace_workspaces__ws_id__attach_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachInstructionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peek_workspace_workspaces__ws_id__peek_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePeekView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_pane_workspaces__ws_id__pane_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePaneView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_commits_workspaces__ws_id__commits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitSummaryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_sessions_workspaces__ws_id__sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_session_turns_workspaces__ws_id__sessions__session_id__turns_get: {
        parameters: {
            query?: {
                last?: number | null;
            };
            header?: never;
            path: {
                ws_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_branches_branches_get: {
        parameters: {
            query: {
                repo: string;
                scope: "local" | "remote";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
