/**
 * Fail if any source file under `webapp/` is invisible to git.
 *
 * WHY: the repo-root `.gitignore` carries a Python `lib/` rule, and it swept up
 * `webapp/lib/` — the entire data layer. The failure is SILENT in both
 * directions: `git add webapp/lib/x.ts` refuses with a message people skim,
 * and a bare `git add webapp` skips the tree without a word, so the work reads
 * as committed while being untracked. Nineteen files nearly went that way.
 *
 * No typechecker or test can see this, because the files are all present on
 * disk. Only git's own opinion of them reveals it — so we ask git.
 */

import { execFileSync, spawnSync } from "node:child_process";
import { readdirSync } from "node:fs";
import { join, relative } from "node:path";

const SOURCE = /\.(ts|tsx|css|mjs)$/;

/** Directories that are SUPPOSED to be ignored — build output and installs. */
const EXPECTED_IGNORED = new Set(["node_modules", ".next", "test-results", ".auth", "coverage"]);

/** Generated by `next dev`, legitimately ignored, and never ours to commit. */
const EXPECTED_IGNORED_FILES = new Set(["next-env.d.ts"]);

function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (EXPECTED_IGNORED.has(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...sourceFiles(path));
    else if (SOURCE.test(entry.name) && !EXPECTED_IGNORED_FILES.has(entry.name)) out.push(path);
  }
  return out;
}

function main(): void {
  const root = process.cwd();
  const repoRoot = execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" }).trim();
  const files = sourceFiles(root).map((path) => relative(repoRoot, path));

  // `check-ignore --stdin` echoes only the paths git would ignore. It exits 1
  // when that set is empty — the PASSING case — so this cannot use a throwing
  // exec; only an exit above 1 is a real error.
  const result = spawnSync("git", ["check-ignore", "--stdin"], {
    cwd: repoRoot,
    input: files.join("\n"),
    encoding: "utf8",
  });
  if (result.status !== null && result.status > 1) {
    console.error(`✗ check:ignored — git check-ignore failed: ${result.stderr}`);
    process.exit(1);
  }

  const ignored = result.stdout.trim() ? result.stdout.trim().split("\n") : [];
  if (ignored.length === 0) {
    console.log(`✓ check:ignored — all ${files.length} source files under webapp/ are visible to git.`);
    return;
  }

  console.error(`\n✗ check:ignored — ${ignored.length} source file(s) under webapp/ are IGNORED by git:\n`);
  for (const path of ignored) console.error(`    ${path}`);
  console.error(
    "\n  These look committed and are not. Find the offending rule with\n" +
      `    git check-ignore -v ${ignored[0]}\n` +
      "  then add a negation for this path to the repo-root .gitignore\n" +
      "  (the existing `!/webapp/lib` pair is the precedent).\n",
  );
  process.exit(1);
}

main();
