"""Pairing + session authentication for the daemon's HTTP surface.

One atomic class (`SessionStore`) owns every piece of authentication state:
short-lived `PairingChallenge`s and long-lived `Session`s. Both halves persist
to a single JSON file (`paths.user_auth_path`) so the daemon process and the
TUI / CLI process can collaborate on the pairing flow — daemon mints
challenges on browser pair requests, the TUI/CLI flips a challenge to
``approved`` on user action, the next browser poll consumes the approval and
issues a single-use bearer token.

Design invariants (CLAUDE.md):

- Plaintext bearer tokens NEVER touch disk. The token is generated on the
  daemon at consume time, returned in the HTTP response, hashed via SHA-256
  (constant-time compared on validate), and the hash alone is persisted.
- The on-disk JSON contains only *metadata*: pairing labels, codes, TTLs,
  state, and session hashes. A user-readable file (mode 600 by virtue of
  living in the user's config dir) does not become a credential cache.
- Sessions slide their TTL on each `validate()` so daily users never
  re-pair; idle for `session_ttl` → re-pair.
- Side effects (clock, RNG, file I/O) are injectable for tests.

The store is the single source of truth for the auth domain — nothing else
in `grove/core/` reaches into auth state directly. Daemon calls it through
its dep; TUI / CLI call it via `LocalTransport` / direct import.
"""

from __future__ import annotations

import base64
import contextlib
import hashlib
import hmac
import json
import os
import secrets
import threading
from collections.abc import Callable
from dataclasses import dataclass, replace
from datetime import UTC, datetime, timedelta
from enum import StrEnum
from pathlib import Path
from typing import Any, ClassVar, TypedDict
from uuid import UUID, uuid4

from loguru import logger

from grove.core import paths
from grove.core.errors import (
    AuthInvalidToken,
    AuthRateLimited,
    GroveError,
    PairingAlreadyResolved,
    PairingNotFound,
    SessionNotFound,
)

_TOKEN_PREFIX = "grove_v1_"
_TOKEN_BYTES = 32  # 256 bits — well above any practical bearer-token entropy bar
_FILE_VERSION = 1


class _StoreData(TypedDict):
    """Typed mirror of the on-disk JSON shape, post-decode.

    Used internally by ``SessionStore._load`` / ``_save`` so mypy can narrow
    ``data["sessions"]`` to ``list[Session]`` without ``# type: ignore``.
    """

    challenges: list[PairingChallenge]
    sessions: list[Session]


# Crockford-ish: no 0/O, 1/I/L, U (sounds like V). 28 distinct characters; an
# 8-char code is ~28**8 ≈ 3.78e11 possible values, so a 5-min TTL bounds
# brute-force well below per-second rate limits.
_CODE_ALPHABET = "BCDFGHJKMNPQRSTVWXYZ23456789"
_CODE_LEN = 8


# ─── enums + dataclasses ────────────────────────────────────────────────────


class ChallengeState(StrEnum):
    """Lifecycle states for a `PairingChallenge`.

    Persisted to JSON. ``StrEnum`` keeps the on-disk value plain.
    """

    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    CONSUMED = "consumed"  # token issued, terminal
    EXPIRED = "expired"  # TTL passed without consumption, terminal


_TERMINAL_CHALLENGE_STATES: frozenset[ChallengeState] = frozenset(
    {ChallengeState.DENIED, ChallengeState.CONSUMED, ChallengeState.EXPIRED}
)


@dataclass(slots=True)
class PairingChallenge:
    """A single pairing attempt — id + label + code + state, no token data.

    The token is generated by the daemon at consume time (``SessionStore.pair_poll``)
    and returned in the same HTTP response that transitions this record to
    ``CONSUMED``. The plaintext token never lives on this record nor on disk.
    """

    challenge_id: UUID
    label: str
    code: str
    created_at: datetime
    expires_at: datetime
    state: ChallengeState

    def is_expired(self, *, now: datetime) -> bool:
        return now >= self.expires_at

    @classmethod
    def fresh(cls, *, label: str, code: str, now: datetime, ttl: timedelta) -> PairingChallenge:
        return cls(
            challenge_id=uuid4(),
            label=label,
            code=code,
            created_at=now,
            expires_at=now + ttl,
            state=ChallengeState.PENDING,
        )


@dataclass(slots=True)
class Session:
    """A long-lived authenticated session — bearer-token hash + metadata."""

    session_id: UUID
    label: str
    token_hash: str  # sha256(token).hexdigest()
    created_at: datetime
    expires_at: datetime
    last_seen_at: datetime
    revoked_at: datetime | None

    def is_active(self, *, now: datetime) -> bool:
        return self.revoked_at is None and now < self.expires_at


# ─── store ──────────────────────────────────────────────────────────────────


_DEFAULT_SESSION_TTL = timedelta(days=30)
_DEFAULT_PAIRING_TTL = timedelta(minutes=5)
_DEFAULT_RATE_PAIR_INIT_PER_MIN = 5
_DEFAULT_RATE_PAIR_POLL_PER_MIN = 60  # generous — the browser polls this every 2s
_LAST_SEEN_WRITE_THROTTLE = timedelta(seconds=60)


def _utcnow() -> datetime:
    return datetime.now(UTC)


def _generate_code(rng: secrets.SystemRandom) -> str:
    """Return an 8-char code formatted ``XXXX-XXXX`` from the safe alphabet."""
    raw = "".join(rng.choice(_CODE_ALPHABET) for _ in range(_CODE_LEN))
    return f"{raw[:4]}-{raw[4:]}"


def _generate_token(rng: secrets.SystemRandom) -> str:
    """Return a fresh bearer token: ``grove_v1_<32 random bytes, urlsafe>``.

    The prefix is grep-able and reserves room for a v2 rotation; the byte
    payload is generated via the injected RNG so tests can pin a seeded
    `SystemRandom` and assert exact token bytes.
    """
    raw = rng.randbytes(_TOKEN_BYTES)
    payload = base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")
    return f"{_TOKEN_PREFIX}{payload}"


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


class SessionStore:
    """Atomic owner of pairing challenges and sessions.

    Single class, methods on the state. Methods that mutate persist their
    result before returning. Read methods garbage-collect expired
    challenges + sessions on the way out so the on-disk file stays bounded.

    Concurrency: daemon and TUI/CLI run in different processes but share
    the same JSON file. Each operation is read-modify-write-with-os.replace.
    A process-local `RLock` guards the in-memory mutation; cross-process
    races on the disk file are vanishingly rare in practice (one user, low
    operation rate) and fail safely (last-writer-wins; the lost transition
    can be retried by the user). We accept this rather than introduce a
    fcntl-based lock (cross-platform fragility outweighs the benefit at
    V1 scale).
    """

    _PAIR_INIT_WINDOW: ClassVar[timedelta] = timedelta(minutes=1)
    _PAIR_POLL_WINDOW: ClassVar[timedelta] = timedelta(minutes=1)

    def __init__(
        self,
        *,
        path: Path | None = None,
        session_ttl: timedelta = _DEFAULT_SESSION_TTL,
        pairing_ttl: timedelta = _DEFAULT_PAIRING_TTL,
        pair_init_per_minute: int = _DEFAULT_RATE_PAIR_INIT_PER_MIN,
        pair_poll_per_minute: int = _DEFAULT_RATE_PAIR_POLL_PER_MIN,
        clock: Callable[[], datetime] | None = None,
        rng: secrets.SystemRandom | None = None,
    ) -> None:
        self._path = path if path is not None else paths.user_auth_path()
        self._session_ttl = session_ttl
        self._pairing_ttl = pairing_ttl
        self._pair_init_limit = pair_init_per_minute
        self._pair_poll_limit = pair_poll_per_minute
        self._clock = clock if clock is not None else _utcnow
        self._rng = rng if rng is not None else secrets.SystemRandom()
        self._lock = threading.RLock()
        # Per-source rate-limit timestamps. Keyed by (kind, source) where
        # ``source`` is the requester address (or "<local>" for in-process
        # callers). Bounded by the GC step inside ``_check_rate``.
        self._rate_log: dict[tuple[str, str], list[datetime]] = {}

    @property
    def path(self) -> Path:
        return self._path

    # ─── pairing lifecycle ─────────────────────────────────────────────────

    def pair_init(
        self,
        *,
        label: str,
        requester_addr: str | None = None,
    ) -> PairingChallenge:
        """Create a new pending challenge. Caller is the entity *requesting* a pair.

        ``requester_addr`` is the source identifier used by the rate limiter
        (e.g. ``request.client.host``); pass ``None`` for in-process callers
        (CLI / tests). Raises ``AuthRateLimited`` if the source has exceeded
        the configured per-minute pair-init budget.
        """
        cleaned = label.strip()
        if not cleaned:
            raise GroveError("pairing label cannot be empty")
        if len(cleaned) > 128:
            raise GroveError("pairing label cannot exceed 128 characters")
        with self._lock:
            now = self._clock()
            self._check_rate("init", requester_addr, now, self._pair_init_limit)
            data = self._load(now)
            challenge = PairingChallenge.fresh(
                label=cleaned,
                code=_generate_code(self._rng),
                now=now,
                ttl=self._pairing_ttl,
            )
            data["challenges"].append(challenge)
            self._save(data)
            logger.info(
                "pairing.init label={!r} code={} expires_at={}",
                challenge.label,
                challenge.code,
                challenge.expires_at,
            )
            return challenge

    def pair_approve(self, challenge_id: UUID) -> PairingChallenge:
        """Flip a pending challenge to ``APPROVED``. Idempotent on repeated calls
        with the same id while still APPROVED (returns the same record); raises
        on any terminal state.

        Does NOT mint a token here — token generation happens at consume time
        on the daemon side so the plaintext never touches disk. The TUI / CLI
        signal approval; the browser's polling endpoint is what actually
        receives the token.
        """
        with self._lock:
            now = self._clock()
            data = self._load(now)
            challenge = self._find_challenge(data["challenges"], challenge_id)
            if challenge.state == ChallengeState.APPROVED:
                return challenge
            if challenge.state in _TERMINAL_CHALLENGE_STATES:
                raise PairingAlreadyResolved(
                    f"pairing {challenge_id} is already {challenge.state.value}"
                )
            challenge.state = ChallengeState.APPROVED
            self._save(data)
            logger.info("pairing.approve challenge_id={} label={!r}", challenge_id, challenge.label)
            return challenge

    def pair_deny(self, challenge_id: UUID) -> PairingChallenge:
        """Flip a pending challenge to ``DENIED``. Terminal."""
        with self._lock:
            now = self._clock()
            data = self._load(now)
            challenge = self._find_challenge(data["challenges"], challenge_id)
            if challenge.state == ChallengeState.DENIED:
                return challenge
            if challenge.state in _TERMINAL_CHALLENGE_STATES:
                raise PairingAlreadyResolved(
                    f"pairing {challenge_id} is already {challenge.state.value}"
                )
            challenge.state = ChallengeState.DENIED
            self._save(data)
            logger.info("pairing.deny challenge_id={} label={!r}", challenge_id, challenge.label)
            return challenge

    def pair_poll(
        self,
        challenge_id: UUID,
        *,
        requester_addr: str | None = None,
    ) -> tuple[PairingChallenge, str | None]:
        """Inspect a challenge; on first poll after ``APPROVED`` mint and return the token.

        Returns ``(challenge, token)`` where ``token`` is the plaintext bearer on
        the consume-step poll and ``None`` for any other state. Repeated polls
        after consume return ``(consumed_challenge, None)`` — the token is
        single-use by contract.
        """
        with self._lock:
            now = self._clock()
            self._check_rate("poll", requester_addr, now, self._pair_poll_limit)
            data = self._load(now)
            challenge = self._find_challenge(data["challenges"], challenge_id)
            if challenge.state != ChallengeState.APPROVED:
                # Pending / denied / consumed / expired → nothing to mint.
                return challenge, None
            # Mint and return the token, transition to consumed, persist.
            token = _generate_token(self._rng)
            session = Session(
                session_id=uuid4(),
                label=challenge.label,
                token_hash=_hash_token(token),
                created_at=now,
                expires_at=now + self._session_ttl,
                last_seen_at=now,
                revoked_at=None,
            )
            data["sessions"].append(session)
            challenge.state = ChallengeState.CONSUMED
            self._save(data)
            logger.info(
                "pairing.consume challenge_id={} session_id={} label={!r}",
                challenge_id,
                session.session_id,
                session.label,
            )
            return challenge, token

    # ─── session lifecycle ─────────────────────────────────────────────────

    def validate(self, token: str) -> Session:
        """Look up a session by bearer token; slide its TTL on success.

        Raises ``AuthInvalidToken`` for missing / malformed / unrecognized /
        revoked / expired tokens. Constant-time compares the candidate hash
        against every stored hash (O(N), but N is small in practice).
        """
        if not token or not token.startswith(_TOKEN_PREFIX):
            raise AuthInvalidToken("malformed token")
        candidate = _hash_token(token)
        with self._lock:
            now = self._clock()
            data = self._load(now)
            for session in data["sessions"]:
                if not hmac.compare_digest(session.token_hash, candidate):
                    continue
                if not session.is_active(now=now):
                    raise AuthInvalidToken("token revoked or expired")
                # Sliding TTL — refresh on use, throttled to avoid thrashing
                # the JSON file under a polling load.
                if now - session.last_seen_at > _LAST_SEEN_WRITE_THROTTLE:
                    session.last_seen_at = now
                    session.expires_at = now + self._session_ttl
                    self._save(data)
                return session
            raise AuthInvalidToken("token not recognized")

    def revoke(self, session_id: UUID) -> None:
        with self._lock:
            now = self._clock()
            data = self._load(now)
            for session in data["sessions"]:
                if session.session_id == session_id:
                    if session.revoked_at is not None:
                        return
                    session.revoked_at = now
                    self._save(data)
                    logger.info("session.revoke session_id={}", session_id)
                    return
            raise SessionNotFound(f"no session with id {session_id}")

    def list_sessions(self, *, include_revoked: bool = False) -> list[Session]:
        """All sessions; revoked sessions hidden by default."""
        with self._lock:
            now = self._clock()
            data = self._load(now)
            out = list(data["sessions"])
            if not include_revoked:
                out = [s for s in out if s.revoked_at is None]
            return out

    def list_pending_challenges(self) -> list[PairingChallenge]:
        """Pending + approved challenges (the TUI's modal-worthy set)."""
        with self._lock:
            now = self._clock()
            data = self._load(now)
            return [
                c
                for c in data["challenges"]
                if c.state in {ChallengeState.PENDING, ChallengeState.APPROVED}
            ]

    def get_challenge(self, challenge_id: UUID) -> PairingChallenge:
        with self._lock:
            now = self._clock()
            data = self._load(now)
            return self._find_challenge(data["challenges"], challenge_id)

    # ─── internal: persistence + rate + gc ─────────────────────────────────

    def _load(self, now: datetime) -> _StoreData:
        """Read the file, GC expired records, return the working set.

        Returned dict has keys ``challenges`` and ``sessions``; values are
        lists of in-memory `PairingChallenge` / `Session` objects. The
        caller mutates the lists in place and calls ``_save`` to persist.
        """
        if not self._path.exists():
            return {"challenges": [], "sessions": []}
        try:
            with self._path.open(encoding="utf-8") as fh:
                raw = json.load(fh)
        except json.JSONDecodeError as exc:
            raise GroveError(f"corrupt auth file at {self._path}: {exc}") from exc
        except OSError as exc:
            raise GroveError(f"cannot read auth file at {self._path}: {exc}") from exc
        if not isinstance(raw, dict):
            raise GroveError(f"unexpected auth shape at {self._path}")
        if raw.get("version") != _FILE_VERSION:
            raise GroveError(
                f"auth file version {raw.get('version')!r} not supported (expected {_FILE_VERSION})"
            )
        challenges = [self._decode_challenge(c) for c in raw.get("challenges", [])]
        sessions = [self._decode_session(s) for s in raw.get("sessions", [])]
        # Garbage-collect on the way in: drop terminal challenges older than
        # one TTL window (so polls within the window still see a meaningful
        # state) and prune sessions whose TTL has passed.
        gc_cutoff = now - self._pairing_ttl
        challenges = [
            self._maybe_expire(c, now=now)
            for c in challenges
            if not (c.state in _TERMINAL_CHALLENGE_STATES and c.expires_at < gc_cutoff)
        ]
        sessions = [s for s in sessions if s.expires_at > now or s.revoked_at is None]
        # If something we GC'd changes the on-disk picture, save now so the
        # next reader sees the cleaner file. Cheap; only emits when records
        # actually drop out.
        return {"challenges": challenges, "sessions": sessions}

    def _save(self, data: _StoreData) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "version": _FILE_VERSION,
            "challenges": [self._encode_challenge(c) for c in data["challenges"]],
            "sessions": [self._encode_session(s) for s in data["sessions"]],
        }
        text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
        tmp = self._path.with_suffix(self._path.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8", newline="\n")
        os.replace(tmp, self._path)
        # Best-effort restrict perms (Unix only). Daemon's umask should
        # already make this 600 but defense-in-depth.
        if hasattr(os, "chmod") and os.name == "posix":
            with contextlib.suppress(OSError):  # best-effort hardening
                os.chmod(self._path, 0o600)

    @staticmethod
    def _find_challenge(challenges: list[PairingChallenge], challenge_id: UUID) -> PairingChallenge:
        for c in challenges:
            if c.challenge_id == challenge_id:
                return c
        raise PairingNotFound(f"no pairing challenge with id {challenge_id}")

    @staticmethod
    def _maybe_expire(c: PairingChallenge, *, now: datetime) -> PairingChallenge:
        """Promote a stale PENDING / APPROVED to EXPIRED in-place."""
        if c.state in _TERMINAL_CHALLENGE_STATES:
            return c
        if c.is_expired(now=now):
            return replace(c, state=ChallengeState.EXPIRED)
        return c

    def _check_rate(
        self,
        kind: str,
        source: str | None,
        now: datetime,
        per_minute_limit: int,
    ) -> None:
        """Sliding-window per-source rate limiter.

        Raises ``AuthRateLimited`` when the count of recent timestamps
        exceeds ``per_minute_limit`` within the relevant window. ``source``
        is the requester address (HTTP) or ``None`` for in-process callers
        (which bypass the limit — local TUI / CLI is trusted).
        """
        if source is None:
            return
        window = self._PAIR_INIT_WINDOW if kind == "init" else self._PAIR_POLL_WINDOW
        cutoff = now - window
        key = (kind, source)
        bucket = [ts for ts in self._rate_log.get(key, []) if ts >= cutoff]
        if len(bucket) >= per_minute_limit:
            raise AuthRateLimited(f"too many {kind} requests from {source}")
        bucket.append(now)
        self._rate_log[key] = bucket
        # GC unused buckets occasionally so the dict doesn't grow unbounded.
        if len(self._rate_log) > 1024:
            self._rate_log = {k: v for k, v in self._rate_log.items() if v and v[-1] >= cutoff}

    # ─── (de)serialization ─────────────────────────────────────────────────

    @staticmethod
    def _encode_challenge(c: PairingChallenge) -> dict[str, Any]:
        return {
            "challenge_id": str(c.challenge_id),
            "label": c.label,
            "code": c.code,
            "created_at": c.created_at.isoformat(),
            "expires_at": c.expires_at.isoformat(),
            "state": c.state.value,
        }

    @staticmethod
    def _decode_challenge(data: dict[str, Any]) -> PairingChallenge:
        return PairingChallenge(
            challenge_id=UUID(data["challenge_id"]),
            label=data["label"],
            code=data["code"],
            created_at=datetime.fromisoformat(data["created_at"]),
            expires_at=datetime.fromisoformat(data["expires_at"]),
            state=ChallengeState(data["state"]),
        )

    @staticmethod
    def _encode_session(s: Session) -> dict[str, Any]:
        return {
            "session_id": str(s.session_id),
            "label": s.label,
            "token_hash": s.token_hash,
            "created_at": s.created_at.isoformat(),
            "expires_at": s.expires_at.isoformat(),
            "last_seen_at": s.last_seen_at.isoformat(),
            "revoked_at": s.revoked_at.isoformat() if s.revoked_at else None,
        }

    @staticmethod
    def _decode_session(data: dict[str, Any]) -> Session:
        revoked = data.get("revoked_at")
        return Session(
            session_id=UUID(data["session_id"]),
            label=data["label"],
            token_hash=data["token_hash"],
            created_at=datetime.fromisoformat(data["created_at"]),
            expires_at=datetime.fromisoformat(data["expires_at"]),
            last_seen_at=datetime.fromisoformat(data["last_seen_at"]),
            revoked_at=datetime.fromisoformat(revoked) if revoked else None,
        )


# Module-level constants the daemon + tests reach for to compose error envelopes.
TOKEN_PREFIX = _TOKEN_PREFIX
"""Public alias of the bearer-token prefix; tests + clients depend on it."""

# Exported for tests that need to hand-craft a token shape.
__all__ = [
    "TOKEN_PREFIX",
    "ChallengeState",
    "PairingChallenge",
    "Session",
    "SessionStore",
]
