export const FIXTURE_WORKSPACES = [
  {
    id: "w-grove-1",
    title: "feat dashboard",
    repo_root: "/repos/Grove",
    branch: "kk/feat-dashboard",
    base_branch: "main",
    worktree_path: "/repos/Grove/.worktrees/dash",
    tmux_session: "grove-dash",
    agent_name: "claude",
    status: "active",
    created_at: "2026-05-09T10:00:00Z",
    updated_at: "2026-05-09T10:30:00Z",
    paused_at: null,
    error_detail: null,
    description: null,
    init_status: "ok",
    init_duration_ms: 350,
    branch_provenance: "grove",
  },
  {
    id: "w-grove-2",
    title: "fix tests",
    repo_root: "/repos/Grove",
    branch: "kk/fix-tests",
    base_branch: "main",
    worktree_path: "/repos/Grove/.worktrees/tests",
    tmux_session: "grove-tests",
    agent_name: "claude",
    status: "idle",
    created_at: "2026-05-09T08:00:00Z",
    updated_at: "2026-05-09T09:30:00Z",
    paused_at: null,
    error_detail: null,
    description: null,
    init_status: "ok",
    init_duration_ms: 220,
    branch_provenance: "grove",
  },
  {
    id: "w-other-1",
    title: "spike",
    repo_root: "/repos/website",
    branch: "spike/refactor",
    base_branch: "main",
    worktree_path: "/repos/website/.worktrees/spike",
    tmux_session: "site-spike",
    agent_name: "claude",
    status: "orphaned",
    created_at: "2026-04-09T08:00:00Z",
    updated_at: "2026-04-10T08:00:00Z",
    paused_at: null,
    error_detail: null,
    description: null,
    init_status: "skipped",
    init_duration_ms: 0,
    branch_provenance: "user",
  },
];

export const FIXTURE_PEEK_W_GROVE_1 = {
  state: FIXTURE_WORKSPACES[0],
  base_ahead: 3,
  base_behind: 0,
  diff_added: 124,
  diff_removed: 17,
  dirty_files: 2,
  recent_commits: [
    { sha: "abc1234567", subject: "feat: scaffold dashboard", committed_at: "2026-05-09T10:25:00Z" },
    { sha: "def4567890", subject: "feat: card component", committed_at: "2026-05-09T10:10:00Z" },
  ],
  agent_snapshot: "$ npm run dev\n> next dev\n  ready in 1.2s\n",
  snapshot_taken_at: "2026-05-09T10:30:00Z",
};
